/* Generated by Yosys 0.68+post (git sha1 c12172fbae8af5e20f6fb52e3d4e92d56ed587b6, Release, AppleClang clang++ 21.0.0.21000101) */

module instruction_memory(address, instruction);
  input [7:0] address;
  wire [7:0] address;
  output [15:0] instruction;
  wire [15:0] instruction;
  wire [15:0] _00_;
  wire [15:0] _01_;
  wire [15:0] _02_;
  wire [15:0] _03_;
  wire [15:0] _04_;
  wire [15:0] _05_;
  wire [15:0] _06_;
  wire [15:0] _07_;
  wire [15:0] _08_;
  wire [15:0] _09_;
  wire [15:0] _10_;
  wire [15:0] _11_;
  wire [15:0] _12_;
  wire [15:0] _13_;
  wire [15:0] _14_;
  assign instruction = address[7] ? 16'h0000 : _00_;
  assign _00_ = address[6] ? 16'h0000 : _01_;
  assign _01_ = address[5] ? 16'h0000 : _02_;
  assign _02_ = address[4] ? 16'h0000 : _03_;
  assign _03_ = address[3] ? _05_ : _04_;
  assign _04_ = address[2] ? _07_ : _06_;
  assign _05_ = address[2] ? 16'h0000 : _08_;
  assign _06_ = address[1] ? _10_ : _09_;
  assign _07_ = address[1] ? _12_ : _11_;
  assign _08_ = address[1] ? _14_ : _13_;
  assign _09_ = address[0] ? 16'h1405 : 16'h120c;
  assign _10_ = address[0] ? 16'h4680 : 16'h2640;
  assign _11_ = address[0] ? 16'h6280 : 16'h5280;
  assign _12_ = address[0] ? 16'h182a : 16'h7280;
  assign _13_ = address[0] ? 16'h8a14 : 16'h9814;
  assign _14_ = address[0] ? 16'hf000 : 16'h0000;
endmodule
