/* Generated by Yosys 0.68+post (git sha1 c12172fbae8af5e20f6fb52e3d4e92d56ed587b6, Release, AppleClang clang++ 21.0.0.21000101) */

module instruction_memory(address, instruction);
  input [7:0] address;
  wire [7:0] address;
  output [15:0] instruction;
  wire [15:0] instruction;
  wire signed [31:0] i;
  assign i = 32'd256;
  assign instruction = 16'h0000;
endmodule
