`timescale 1ns/1ps

module minirisc_assembler_tb;

    reg clk;
    reg reset;

    wire [7:0]  pc;
    wire [15:0] instruction;
    wire [2:0]  state;

    wire zero;
    wire carry;
    wire halted;


    // ============================================================
    // MINIRISC CPU
    //
    // IMPORTANT:
    // This CPU is now loading the file generated by Python.
    // ============================================================

    minirisc_cpu #(
        .PROGRAM_FILE("programs/assembled_program.mem")
    ) dut (
        .clk(clk),
        .reset(reset),

        .pc_debug(pc),
        .instruction_debug(instruction),
        .state_debug(state),

        .zero_debug(zero),
        .carry_debug(carry),

        .halted(halted)
    );


    // ============================================================
    // CLOCK
    // ============================================================

    initial begin
        clk = 0;
        forever #5 clk = ~clk;
    end


    // ============================================================
    // TEST
    // ============================================================

    initial begin

        $dumpfile("sim/minirisc_assembler.vcd");
        $dumpvars(0, minirisc_assembler_tb);


        // --------------------------------------------------------
        // Reset CPU
        // --------------------------------------------------------

        reset = 1;

        #12;

        reset = 0;


        // --------------------------------------------------------
        // Run assembled program
        // --------------------------------------------------------

        #220;


        $display("");
        $display("==========================================");
        $display("       ASSEMBLER -> CPU TEST");
        $display("==========================================");


        // ========================================================
        // CHECK R1
        //
        // Program:
        //
        // LDI R1,5
        // LDI R2,3
        // ADD R1,R2
        //
        // Therefore R1 should become 8
        // ========================================================

        if (dut.u_regfile.registers[1] == 8'd8)
            $display(
                "PASS: R1 = 8"
            );
        else
            $display(
                "FAIL: R1 should be 8, actual = %d",
                dut.u_regfile.registers[1]
            );


        // ========================================================
        // CHECK R2
        // ========================================================

        if (dut.u_regfile.registers[2] == 8'd3)
            $display(
                "PASS: R2 = 3"
            );
        else
            $display(
                "FAIL: R2 should be 3, actual = %d",
                dut.u_regfile.registers[2]
            );


        // ========================================================
        // CHECK DATA MEMORY
        //
        // STORE R1,10
        //
        // Therefore memory[10] should contain 8
        // ========================================================

        if (dut.u_dmem.memory[10] == 8'd8)
            $display(
                "PASS: Memory[10] = 8"
            );
        else
            $display(
                "FAIL: Memory[10] should be 8, actual = %d",
                dut.u_dmem.memory[10]
            );


        // ========================================================
        // CHECK HALT
        // ========================================================

        if (halted == 1'b1)
            $display(
                "PASS: CPU halted"
            );
        else
            $display(
                "FAIL: CPU should be halted"
            );


        // ========================================================
        // FINAL VALUES
        // ========================================================

        $display("");
        $display("------------------------------------------");

        $display(
            "Final R1       = %d",
            dut.u_regfile.registers[1]
        );

        $display(
            "Final R2       = %d",
            dut.u_regfile.registers[2]
        );

        $display(
            "Final Memory10 = %d",
            dut.u_dmem.memory[10]
        );

        $display(
            "Final PC       = %d",
            pc
        );

        $display(
            "Final Halted   = %b",
            halted
        );

        $display("------------------------------------------");

        $display("");
        $display("==========================================");
        $display("   ASSEMBLER -> CPU TEST COMPLETE");
        $display("==========================================");


        $finish;

    end

endmodule